New Controller: OperatioJob, support Replace (#233)
* import kruise v1.4.0

* ensure TTL and activeDeadline

* support admission webhook

* rephase spec.partition

* support feature partition

* fix bug: replace same targets by partition

* rename file: pkg/controllers/operationjob/recreate

* rename file: pkg/controllers/operationjob/utils/finalizer.go

* add annotation to register recreate interface

* fix collaset ut: remove operationDelays

* validating webhook: deny partition decreased

* (1) not check pod exist in webhook; (2) support recreate non exist pod; (3) refactor podOpsStatus extraInfo

* add ReleaseTarget (TODO)

* refactor directory and structs

* (1) parally execute recreate and update; (2) release target when delete oj

* add ut for deadline and TTL

* deleteExpectation after targets released when deletionTimestamp not nil

* refactor job and pod operation progress

* api: remove ExtraInfo, add Reason, Message

* validating webhook: targets filed is immutable

* add observedGeneration

* stop operate target if job finished

* update and recreate execute parallel

* reset collaset ut

* remove finalizer utils, and use exist utils

* operation delay seconds

* add reason: ReplaceByNewPod

* operationjob validating webhook simplified

* move recreatMethod Anno from oj to pod

* add charts of oj

* support replace-oj deleted and cancel replace

* operationJob e2e

* add featuregate: EnableKruiseToRecreate

* (1) choose to import kruise api; (2) add ReasonInvalidRecreateMethod

* Action: Recreate -> Restart

* fix: finish restart ops lifecycle is operation finished

* fix: continue to operate target if ops finished, to clean some lifecycle

* fix: do not panic when opsAction not supported

* operate candidata using slowStartBatch with goroutine

* refactor operationjob api: opsStatus and targetDetails

* fix golint

* take out common codes of ActionOperater

* fix: ReleaseTargetsForDeletion npe

* (1) re-defein crr name; (2) register crr to new cache if EnableKruiseToRestart=true

* fix golint

* fix golint2

* refactor ActionHandler

* set EnableKruiseToRestart to false by default

* set EnableKruiseToRestart in manager.yaml

* refactor OpsLifecycleAdapter

* remove AnnotationOperationJobRestartMethod

* remove OperateInfo

* refactor KruiseRestartHandler PodReplaceHandler

* refactor ActionHandler

* refactor usingOpsLifecycle logic

* refactor GetOpsProgress

* GetOpsStatus: do not change progress if crr not found

* add note for register

* ensure PodReplaceHandler and KruiseRestartHandler is good to register

* featureGate: EnableKruiseToRestart

* featureGate: EnableKruiseToRestart

* fix replace succeeded reason and message

* refactor register

* add containers for all cnadidate and actions

* refactor handler parameters

* remove redundant file

* webhook validating: add action validate

* improve logger: pass controller's logger to handler

* webhook error: improve webhook respnse

* fix: lifecycle id using oj name

* refactorlifecyle adapter

* add Init() function to action handler

* add Init() function to action handler

* remove redundant lines

* move register actions into main.go

* refactor RegisterOperationJobActions

* action replace only

* update go mod

* update go mod

* lifecycleAdapter => enablePodOpsLifecycle

* oj shoule not be reconciled if failed or succeeded

* oj shoule not be reconciled if failed or succeeded2

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -82,3 +82,71 @@ jobs:
           kubectl get pod -n kusionstack-system --no-headers -l control-plane=controller-manager | awk '{print $1}' | xargs kubectl logs -p -n kusionstack-system
           exit 1
         fi
+
+  OperationJob:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+      - name: Setup Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: ${{ env.GO_VERSION }}
+      - name: Cache Go Dependencies
+        uses: actions/cache@v2
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: ${{ runner.os }}-go-
+      - name: Setup Kind Cluster
+        uses: helm/kind-action@v1.10.0
+        with:
+          node_image: ${{ env.KIND_IMAGE }}
+          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/e2e/scripts/kind-conf.yaml
+          version: ${{ env.KIND_VERSION }}
+      - name: Setup Kube-config
+        run: |
+          mkdir -p /tmp/kind
+          make kind-kube-config
+      - name: Install Operating
+        run: |
+          set -ex
+          kubectl cluster-info
+          make docker-build
+          make sync-kind-image
+          make deploy
+          for ((i=1;i<10;i++));
+          do
+            set +e
+            PODS=$(kubectl get pod -n kusionstack-system | grep -c '1/1')
+            set -e
+            if [ "$PODS" -eq 1 ]; then
+              break
+            fi
+            sleep 3
+          done
+          set -e
+          PODS=$(kubectl get pod -n kusionstack-system | grep -c '1/1')
+          if [ "$PODS" -eq 1 ]; then
+            echo "Wait for Kusionstack-manager ready successfully"
+          else 
+            echo "Timeout to wait for Kusionstack-manager ready"
+          fi
+      - name: Run e2e Tests
+        run: |
+          make ginkgo
+          set -e
+          KUBECONFIG=/tmp/kind/kubeconfig.yaml ./bin/ginkgo -timeout 10m -v --focus='\[apps\] OperationJob' test/e2e
+      - name: Check Operating Manager
+        run: |
+          restartCount=$(kubectl get pod -n kusionstack-system -l control-plane=controller-manager --no-headers | awk '{print $4}')
+          if [ "${restartCount}" -eq "0" ];then
+            echo "Kusionstack-manager has not restarted"
+          else
+            kubectl get pod -n kusionstack-system -l control-plane=controller-manager --no-headers
+            echo "Kusionstack-manager has restarted, abort!!!"
+            kubectl get pod -n kusionstack-system --no-headers -l control-plane=controller-manager | awk '{print $1}' | xargs kubectl logs -p -n kusionstack-system
+            exit 1
+          fi
