enhance e2e ci: (1) test e2e only after manager running; (2) test failed and dump logs if manager crashed

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -45,14 +45,40 @@ jobs:
         mkdir -p /tmp/kind
         make kind-kube-config
         make docker-build
+        make sync-kind-image
     - name: Install Operating
       run: |
-        make sync-kind-image
+        set -ex
+        kubectl cluster-info
         make deploy
+        for ((i=1;i<10;i++));
+        do
+          set +e
+          PODS=$(kubectl get pod -n kusionstack-system | grep -c '1/1')
+          set -e
+          if [ "$PODS" -eq 1 ]; then
+            break
+          fi
+          sleep 3
+        done
+        set -e
+        PODS=$(kubectl get pod -n kusionstack-system | grep -c '1/1')
+        if [ "$PODS" -eq 1 ]; then
+          echo "Wait for Kusionstack-manager ready successfully"
+        else 
+          echo "Timeout to wait for Kusionstack-manager ready"
+        fi
     - name: Run e2e Tests
       run: |
         make ginkgo
+        set -e
         KUBECONFIG=/tmp/kind/kubeconfig.yaml ./bin/ginkgo -timeout 10m -v --focus='\[apps\] CollaSet' test/e2e
-    - name: Clean Kind Cluster
-      run: |
-        make clean-kind
+        restartCount=$(kubectl get pod -n kusionstack-system -l control-plane=controller-manager --no-headers | awk '{print $4}')
+        if [ "${restartCount}" -eq "0" ];then
+          echo "Kusionstack-manager has not restarted"
+        else
+          kubectl get pod -n kusionstack-system -l control-plane=controller-manager --no-headers
+          echo "Kusionstack-manager has restarted, abort!!!"
+          kubectl get pod -n kusionstack-system --no-headers -l control-plane=controller-manager | awk '{print $1}' | xargs kubectl logs -p -n kusionstack-system
+          exit 1
+        fi
